:: This is comment

@echo off

set "BinPath=F:\Games\Steam\steamapps\common\GarrysMod\bin"

set Name=TrackAssembly
set ID=287012681
set Dirs=(lua)

title Addon updater/publisher

echo Press Crtl+C to terminate !
echo Press a key if you dont want to wait ! 
echo Rinning in %CD%.
echo Npp Find --\h{1,}\n-- replace --\n-- in unix format before commit !
echo.  

timeout 10
rd /S /Q %CD%\Workshop
md Workshop\%Name%
for %%i in %Dirs% do (
  echo Extracting %%i
  timeout 3
  xcopy %CD%\%%i %CD%\Workshop\%Name%\%%i /EXCLUDE:%curpath%key.txt /E /C /I /F /R /Y
)
copy %CD%\addon.json %CD%\Workshop\%Name%\addon.json
call %BinPath%\gmad.exe create -folder "%CD%\Workshop\%Name%" -out "%CD%\Workshop\%Name%.gma"
call %BinPath%\gmpublish.exe update -addon "%CD%\Workshop\%Name%.gma" -id "%ID%" -icon "%CD%\icon.jpg" -changes "Generated by Batch!"
echo.
call echo !!! %%Dir[%x%]%% Published !!!
echo.
timeout 500
exit
